version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    user: "${UID}:${GID}"
    volumes:
      - ./backend:/app
      - ./backend/htmlcov:/app/htmlcov
    environment:
      - ENV=development
      - PYTHONPATH=/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    tty: true
    stdin_open: true
